# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G -Djava.net.preferIPv4Stack=true
org.gradle.parallel=true
org.gradle.daemon=false

# IntelliJ IDEA is not yet fully compatible with configuration cache
org.gradle.configuration-cache=false

# Project
group=com.juzizhen

# Common
minecraft_version=1.21.1

# Fabric
yarn_mappings=1.21.1+build.3
loader_version=0.18.4
loom_version=1.17-SNAPSHOT
fabric_api_version=0.116.13+1.21.1
fabric_mod_version=1.0.3

# NeoForge
neo_version=21.1.248
minecraft_version_range=[1.21.1]
loader_version_range=[1,)
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
neoforge_mod_version=1.0.4-beta

# Shared Mod Properties
maven_group=com.juzizhen
mod_id=three_in_one_uncrafting_table
mod_name=Three In One Uncrafting Table
mod_license=GPL-3.0
mod_authors=juzizhen
mod_description=This is a three-in-one uncrafting table.
